---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: mariadb
  labels:
    chart: mariadb
spec:
  chartGitPath: mariadb
  values:
    image: bitnami/mariadb:_
    persistence:
      enabled: false
