---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: mariadb
  namespace: test
  labels:
    chart: mariadb
  annotations:
    flux.weave.works/locked_user: simon <simon@weave.works>
    flux.weave.works/locked: 'true'
    flux.weave.works/locked_msg: '"hh"'
spec:
  chartGitPath: mariadb
  values:
    image: bitnami/mariadb:10.2
    persistence:
      enabled: false
