---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: mariadb
  namespace: test
  labels:
    chart: mariadb
  annotations:
    flux.weave.works/tag.chart-image: glob:10.2*
    flux.weave.works/locked_user: Simo <simon@weave.works>
spec:
  chartGitPath: mariadb
  values:
    image: bitnami/mariadb:10.2.18-ol-7-r9
    persistence:
      enabled: false
