---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: mongodb
  namespace: test
  labels:
    chart: mongodb
  annotations:
    flux.weave.works/locked_user: Simo <simon@weave.works>
    flux.weave.works/locked: 'true'
    flux.weave.works/locked_msg: '"Lock this dude"'
spec:
  chartGitPath: mongodb
  releaseName: mongodb-database
  values:
    image: bitnami/mongodb:3.6.8-ol-7-r13
    imagePullPolicy: IfNotPresent
    persistence:
      enabled: false
