---
apiVersion: helm.integrations.flux.weave.works/v1alpha2
kind: FluxHelmRelease
metadata:
  name: mongodb
  namespace: test
  labels:
    chart: mongodb
  annotations:
    flux.weave.works/locked_user: simon@weave.works
    flux.weave.works/locked: 'true'
    flux.weave.works/locked_msg: dd
spec:
  chartGitPath: mongodb
  releaseName: mongodb-database
  values:
    image: bitnami/mongodb:_
    imagePullPolicy: IfNotPresent
    persistence:
      enabled: false
